name: willpwr
favicon: null
layout_spectrum: 0.06619906448759139
typography_spectrum: 0.7868508698884398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12806632136926055
  lightness: 0.1091708978638053
  saturation: 0.7415589056909084
  rhythmicContrast: 0.3120242084842175
purpose: []
